version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_MYSQL=323538435273.dkr.ecr.ap-northeast-2.amazonaws.com/advertiser-unit-test-mysql
      - docker run
        --name mysql
        -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
        -e MYSQL_ROOT_PASSWORD=root_password
        -e MYSQL_USER=advertiser
        -e MYSQL_PASSWORD=user_password
        -e MYSQL_DATABASE=testing
        -d -p 3306:3306
        $REPOSITORY_URI_MYSQL:latest
      - echo Composer downloading package
      - composer install --no-progress --ignore-platform-reqs
      - php artisan test
