version: '3.7'

services:
  advertiser-api:
    image: ${DOCKER_IMAGE_DIR}advertiser-nginx:${WAS_VERSION}
    build:
      context: .
      dockerfile: .build/nginx.Dockerfile

  php-fpm:
    image: ${DOCKER_IMAGE_DIR}advertiser-php-fpm:${WAS_VERSION}
    build:
      context: .
      dockerfile: .build/php.Dockerfile
