version: '3.7'

services:
  advertiser-api:
    image: ${DOCKER_IMAGE_DIR}advertiser-nginx:${AWS_WAS_VERSION}
    volumes:
      - .:/www_root/app
    build:
      args:
        APP_ENV: $APP_ENV
        NGINX_VERSION: $NGINX_VERSION
        ARG_PHP_FPM_CONTAINER: $ARG_PHP_FPM_CONTAINER
        ARG_PHP_FPM_PORT: $ARG_PHP_FPM_PORT
      context: .
      dockerfile: .build/nginx.Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - php-fpm

  php-fpm:
    image: ${DOCKER_IMAGE_DIR}advertiser-php-fpm:${AWS_WAS_VERSION}
    volumes:
      - .:/www_root/app
    build:
      args:
        APP_ENV: $APP_ENV
        PHP_VERSION: $PHP_VERSION
        ARG_PHP_FPM_CONTAINER: $ARG_PHP_FPM_CONTAINER
        ARG_PHP_FPM_PORT: $ARG_PHP_FPM_PORT
      context: .
      dockerfile: .build/php.Dockerfile
