branch-defaults:
  dev:
    environment: studiomate-dev
  master:
    environment: studiomate
  staging:
    environment: studiomate-staging
  qa:
    environment: studiomate-qa
  release:
    environment: studiomate-dev
environment-defaults:
  studiomate-dev:
    branch: null
    repository: null
  studiomate-qa:
    branch: null
    repository: null
global:
  application_name: studiomate
  default_ec2_keyname: TLXstudio
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/PHP 8.0 running on 64bit Amazon Linux 2/3.2.0
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
